# SPDX-FileCopyrightText: 2017 Scott Shawcroft, written for Adafruit Industries
#
# SPDX-License-Identifier: MIT

name: Build CI

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - name: Versions
      run: |
        python3 --version
    - name: Checkout Current Repo
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Pip install Sphinx, pre-commit
      run: |
        pip install --force-reinstall Sphinx sphinx-rtd-theme pre-commit
    - name: Pre-commit hooks
      run: |
        pre-commit run --all-files
    - name: Build docs
      working-directory: docs
      run: sphinx-build -E -W -b html . _build/html
